/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lz69_androidvideoplayer_jni_Test */

#ifndef _Included_com_lz69_androidvideoplayer_jni_Test
#define _Included_com_lz69_androidvideoplayer_jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lz69_androidvideoplayer_jni_Test
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lz69_androidvideoplayer_jni_Test_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
